setwd("./right-simulation")
library(data.table)
library(plyr)
library(dplyr)
library(tidyr)
library(reshape2)
load(file="~gravesj/data/right/results_c0.rda")
results0 <- results %>%  mutate(name = paste0(name,"_b0"))
rm(results)
load(file="~gravesj/data/right/results_c1.rda")
results1 <- results %>%  mutate(name = paste0(name,"_b1"))
rm(results)
load(file="~gravesj/data/right/results_c2.rda")
results2 <- results %>%  mutate(name = paste0(name,"_b2"))
rm(results)
load(file="~gravesj/data/right/results_c3.rda")
results3 <- results %>%  mutate(name = paste0(name,"_b3"))
rm(results)
load(file="~gravesj/data/right/results_c4.rda")
results4 <- results %>%  mutate(name = paste0(name,"_b4"))
rm(results)
load(file="~gravesj/data/right/results_c5.rda")
results5 <- results %>%  mutate(name = paste0(name,"_b5"))
rm(results)
load(file="~gravesj/data/right/results_c6.rda")
results6 <- results %>%  mutate(name = paste0(name,"_b6"))
rm(results)
load(file="~gravesj/data/right/results_c7.rda")
results7 <- results %>%  mutate(name = paste0(name,"_b7"))
rm(results)
load(file="~gravesj/data/right/results_c8.rda")
results8 <- results %>%  mutate(name = paste0(name,"_b8"))
rm(results)
load(file="~gravesj/data/right/results_c9.rda")
results9 <- results %>%  mutate(name = paste0(name,"_b9"))
rm(results)
results <- rbind(results0,results1,results2,results3,results4,results5,results6,results7,results8,results9)

###events summary
DT <- data.table(results)
print("Summary")
summary <- DT[, .N, by = list(resource, preemptive, reactive)]
save(summary,file="~gravesj/data/right/results_sum_c10.rda")

###Costs
source('inputs.R')
source('./simvastatin/counters.R')
source("./clopidogrel/counters.R")
source('./warfarin/counters.R')
source("./main/counters.R")
counters <- c(counters.gen, counters.dapt, counters.simvastatin, counters.warfarin)

source("./costs_ICER.R")
inputs$vN <- 200000*10 #change according to combined count
s1 <- cost.qaly(subset(results,preemptive=="None" & reactive=="None"),inputs)
s2 <- cost.qaly(subset(results,preemptive=="None" & reactive=="Panel"),inputs)
sum_costs <- data.frame(preemptive=c("None","None"),
                        reactive=c("None","Panel"))
print("sum_costs")
cbind(sum_costs,rbind(s1,s2)) %>% mutate(ICER = (lag(dCOST)-dCOST)/(lag(dQALY)-dQALY)) 


###warfarin additional
source("./warfarin/output_cal.R")
print("Warfarin")
warfarin_out(results,inputs)
